name: Test Terraform Connection

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  test:
    runs-on: ubuntu-latest  # or windows-latest if preferred

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2  # Specify your desired Terraform version

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set your AWS access key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set your AWS secret key
          AWS_REGION: us-east-2  # Specify your AWS region
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
